name: "Terraform Apply"

on:
  push:
    branches:
      - master

jobs:
  terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    steps:
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0

      - name: "Setup - Build AWS Credentials"
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: "Setup - Terraform CLI"
        uses: hashicorp/setup-terraform@v1.0.1

      - name: "Run - Terraform Init"
        run: terraform init -input=false

      - name: "Run - Terraform Plan"
        run: terraform plan -out=tfplan -input=false

      - name: "Run - Terraform Apply"
        run: terraform apply -input=false -auto-approve tfplan
